import { ReactNode } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Home, User, LogOut } from "lucide-react";
import Footer from "@/components/Footer"; // Import the Footer component
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

// Import custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define metadata
export const metadata: Metadata = {
  title: "Wikusama Hotel",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900 text-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster richColors />

          {/* Wrapper with Navigation, Main Content, and Footer */}
          <div className="min-h-screen flex flex-col">
            {/* Navigation Bar */}
            <nav className="bg-gray-800 shadow-md p-4">
              <div className="container mx-auto flex justify-between items-center">
                <Link href="/" className="text-2xl font-bold">
                  Wikusama Hotel
                </Link>
                <div className="flex items-center space-x-4">
                  <Link href="/">
                    <Button variant="ghost" className="text-gray-300 hover:text-white">
                      <Home className="mr-2 h-4 w-4" /> Home
                    </Button>
                  </Link>
                  <Link href="/admin">
                    <Button variant="ghost" className="text-gray-300 hover:text-white">
                      <User className="mr-2 h-4 w-4" /> Admin
                    </Button>
                  </Link>
                  <Button variant="destructive" className="text-gray-300 hover:text-white">
                    <LogOut className="mr-2 h-4 w-4" /> Logout
                  </Button>
                </div>
              </div>
            </nav>

            {/* Main Content */}
            <main className="flex-1 bg-gray-900">{children}</main>

            {/* Footer Component */}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
